import '../../styles/globals.css'
import Head from 'next/head'
import Banner from '../components/Banner'
import NavBar from '../components/NavBar'
import SignInBar from '../components/SignInBar'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Chuko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="global-container">
          <SignInBar />
          <Banner />
          <NavBar />
          <div className="container">
            <Component {...pageProps} />
          </div>
        </div>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default MyApp
